/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_dwmblocks.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_statuscmd.c"
#include "bar_winicon.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_systray.c"

/* Other patches */
#include "attachx.c"
#include "cfacts.c"
#include "decorationhints.c"
#include "dragcfact.c"
#include "fullscreen.c"
#include "nomodbuttons.c"
#include "pertag.c"
#include "placemouse.c"
#include "reorganizetags.c"
#include "restartsig.c"
#include "shift.c"
#include "shiftboth.c"
#include "shifttagclients.c"
#include "shiftviewclients.c"
#ifdef XINERAMA
#include "sortscreens.c"
#endif // XINERAMA
#include "sticky.c"
#include "swallow.c"
#include "tagall.c"
#include "tagallmon.c"
#include "tapresize.c"
#include "vanitygaps.c"
#include "warp.c"
#include "zoomswap.c"
#include "dragmfact.c"
#include "seamless_restart.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_centeredmaster.c"
#include "layout_horizgrid.c"
#include "layout_monocle.c"
#include "layout_tile.c"

